name: Deploy Azure Function App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Set project path
      run: echo "PROJECT_PATH=src/FunctionAppHTTPTrigger.csproj" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build the application
      run: dotnet build --configuration Release ${{ env.PROJECT_PATH }}

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish ${{ env.PROJECT_PATH }}

    - name: Zip the published files
      run: |
        cd ./publish
        zip -r ../functionapp.zip .
    
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: function-app-artifact
        path: ./functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        inlineScript: |
          az --version

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Bicep
      run: az bicep install

    - name: Deploy Azure infrastructure with Bicep
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file ./main.bicep \
          --parameters functionAppName=${{ secrets.FUNCTION_APP_NAME }} \
          --location ${{ secrets.AZURE_LOCATION }}

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: function-app-artifact
        path: ./artifact

    - name: Unzip the artifact
      run: |
        unzip ./artifact/functionapp.zip -d ./artifact

    - name: Deploy Function App to Azure
      run: |
        az webapp deploy \
          --name ${{ secrets.FUNCTION_APP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --src-path ./artifact
