name: Deploy .NET 8.0 Isolated Function App

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

 #on:
  #workflow_dispatch:
    #inputs:
      #environment:
        #description: 'Choose environment to deploy'
        #required: true
        #default: 'Dev'
        #type: choice
        #options:
          #- Dev
          #- Test
          #- Stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET 8.x SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Set project path
      run: echo "PROJECT_PATH=src/FunctionAppHTTP.csproj" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build the application
      run: dotnet build --configuration Release ${{ env.PROJECT_PATH }}

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish ${{ env.PROJECT_PATH }} --self-contained false

    - name: Zip the published files
      run: |
        zip -r functionapp.zip ./publish
    
    #- name: Publish artifact
     # uses: actions/upload-artifact@v4
      #with:
       # name: function-app-artifact
        #path: ./functionapp.zip

    # - name: Zip the published files
    #   run: |
    #     cd ./publish
    #     zip -r ../functionapp.zip .
    
    # - name: Publish artifact
    #  uses: actions/upload-artifact@v4
    #   with:
    #     name: function-app-artifact
    #     path: ./functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        inlineScript: |
          az --version

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: >
              {
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
              }
        enable-AzPSSession: true

    - name: Install Bicep
      run: az bicep install

    - name: Deploy Azure infrastructure with Bicep
      run: |
        az deployment group create \
          --resource-group "DefaultResourceGroup-NEU" \
          --template-file bicep/modules/Function_APP.bicep \
          --parameters \
            functionAppName="komatsu-func-app" \
            location="North Europe" \
            storageAccountName="demoteststgacc" \
            appServicePlanName="appservicekomatsu" \
            applicationInsightsName="appinsightskomastufuncapp" \
            logAnalyticsWorkspaceName="law-komatsu-dev"

    # - name: Download artifact
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: function-app-artifact
    #     path: ./artifact

    # - name: Unzip the artifact
    #   run: |
    #    unzip ./artifact/functionapp.zip -d ./artifact

    #- name: Deploy Function to Azure
     # run: |
      #  az webapp deploy \
       #   --name "komatsu-func-app" \
        #  --resource-group "DefaultResourceGroup-NEU" \
         # --src-path ./publish/functionapp.zip

    - name: Deploy Function App to Azure using Zip
      run: |
        az functionapp deployment source config-zip \
         --name "komatsu-func-app" \
         --resource-group "DefaultResourceGroup-NEU" \
         --src ./publish/functionapp.zip

    #- name: Deploy to Azure Function Appuses: azure/functions-action@v1with:app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}package: functionapp.zippublish-type: zip
